<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XmlDocGen.Core\XmlDocGen.Core.csproj" />
    <ProjectReference Include="..\..\tools\ExampleAssembly\ExampleAssembly.csproj" />
  </ItemGroup>

</Project>
