<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>A layered library for generating documentation from .NET XML documentation comments.</Description>
    <PackageTags>.NET XML documentation comments Markdown documentation</PackageTags>
    <IsPackable>true</IsPackable>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RewritePackageReadmeLinks>true</RewritePackageReadmeLinks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>