using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;

namespace XmlDocMarkdown.Core;

internal sealed class MarkdownGenerator
{
	public string? NewLine { get; set; }

	public bool IncludeObsolete { get; set; }

	public bool SkipUnbrowsable { get; set; }

	public bool SkipCompilerGenerated { get; set; }

	public bool NamespacePages { get; set; }

	public XmlDocVisibilityLevel Visibility { get; set; }

	public IReadOnlyList<ExternalDocumentation>? ExternalDocs { get; set; }

	public string? FrontMatter { get; internal set; }

	public IReadOnlyList<NamedText> GenerateOutput(Assembly assembly, XmlDocFile xmlDocFile) =>
		[.. DoGenerateOutput(assembly, xmlDocFile)];

	public static string GetCodeGenComment(string assemblyName) => $"<!-- DO NOT EDIT: generated by xmldocmd for {assemblyName} -->";

	public bool PermalinkPretty { get; internal set; }

	public string? RootPageLocation { get; set; }

	private string ActualNewLine => NewLine ?? Environment.NewLine;

	private IEnumerable<NamedText> DoGenerateOutput(Assembly assembly, XmlDocFile xmlDocFile)
	{
		var extension = GetFileExtension();
		var assemblyName = assembly.GetName().Name!;
		var assemblyFilePath = assembly.Modules.FirstOrDefault()?.FullyQualifiedName;
		var assemblyFileName = assemblyFilePath is not null ? Path.GetFileName(assemblyFilePath) : assemblyName;

		var visibleTypes = assembly
			.DefinedTypes
			.Where(IsVisible)
			.ToList();

		var membersByXmlDocName = visibleTypes
			.Where(x => GetTypeKind(x) is TypeKind.Record or TypeKind.Class or TypeKind.Struct or TypeKind.Interface)
			.SelectMany(x => x.DeclaredMembers)
			.Where(x => x is not TypeInfo && IsVisible(x))
			.Concat(visibleTypes)
			.GroupBy(XmlDocUtility.GetXmlDocRef)
			.ToDictionary(x => x.Key!, x => x.Single());

		var visibleTypeRecords = visibleTypes
			.Select(typeInfo => new
			{
				TypeInfo = typeInfo,
				Path = GetTypeUriName(typeInfo) + ".md",
				ShortName = GetShortName(typeInfo),
				ShortSignature = GetShortSignature(typeInfo),
				Namespace = GetNamespaceName(typeInfo),
				Visibility = GetTypeVisibility(typeInfo),
			})
			.ToList();

		var visibleNamespaceRecords = visibleTypeRecords
			.Where(x => x.TypeInfo.DeclaringType is null)
			.GroupBy(x => x.Namespace)
			.Select(ng => new
			{
				Namespace = ng.Key,
				Types = ng
					.OrderBy(x => x.ShortName, StringComparer.OrdinalIgnoreCase)
					.ThenBy(x => x.Path, StringComparer.OrdinalIgnoreCase)
					.ToList(),
			})
			.OrderBy(x => x.Namespace, StringComparer.OrdinalIgnoreCase)
			.ToList();

		var rootPath = GetAssemblyUriName(assembly);
		var safeAssemblyName = GetSafeName(rootPath);
		RootPageLocation = $"{safeAssemblyName}" + (PermalinkPretty ? "Assembly.md" : ".md");
		var context = new MarkdownContext(xmlDocFile, membersByXmlDocName, assemblyFileName, RootPageLocation);
		yield return CreateNamedText(context.PageLocation, writer =>
		{
			var front = GetFrontMatter(assemblyName, $"{safeAssemblyName}{(PermalinkPretty ? "Assembly" : "")}{extension}");
			if (!string.IsNullOrEmpty(front))
				writer.WriteLine(front!);

			writer.WriteLine($"# {assemblyName} assembly");

			foreach (var group in visibleNamespaceRecords)
			{
				writer.WriteLine();
				writer.WriteLine($"## {group.Namespace} namespace");

				foreach (var typeGroup in group.Types.GroupBy(x => x.Visibility))
				{
					writer.WriteLine();
					writer.WriteLine($"| {(typeGroup.Key == XmlDocVisibilityLevel.Public ? "public" : "internal")} type | description |");
					writer.WriteLine("| --- | --- |");
					foreach (var typeInfo in typeGroup)
					{
						var relative = GetPermalink(typeInfo.Path);
						var safeRelative = GetSafeName(relative);
						if (PermalinkPretty)
							safeRelative += "Type";
						var rel = MakeRelative(context.PageLocation, $"{GetNamespaceUriName(group.Namespace)}/{safeRelative}");
						var typeText = GetShortSignatureMarkdown(typeInfo.ShortSignature, rel);
						var summaryText = GetShortSummaryMarkdown(xmlDocFile, typeInfo.TypeInfo, context);
						writer.WriteLine($"| {typeText} | {summaryText} |");
					}
				}
			}

			writer.WriteLine();
			writer.WriteLine(GetCodeGenComment(assemblyFileName));
		});

		// create separate parent pages for each namespace in the assembly.
		foreach (var group in visibleNamespaceRecords)
		{
			var parentPageLocation = RootPageLocation;
			var parentContext = context;

			if (NamespacePages)
			{
				var namespacePath = group.Namespace;
				var safeNamespacePath = GetSafeName(namespacePath);
				parentPageLocation = $"{safeNamespacePath}Namespace.md";
				parentContext = new MarkdownContext(context, null, parentPageLocation);
				yield return CreateNamedText(parentPageLocation, writer =>
				{
					var front = GetFrontMatter(namespacePath, $"{safeNamespacePath}Namespace");
					if (!string.IsNullOrEmpty(front))
						writer.WriteLine(front!);

					writer.WriteLine($"## {group.Namespace} namespace");

					foreach (var typeGroup in group.Types.GroupBy(x => x.Visibility))
					{
						writer.WriteLine();
						writer.WriteLine($"| {(typeGroup.Key == XmlDocVisibilityLevel.Public ? "public" : "internal")} type | description |");
						writer.WriteLine("| --- | --- |");
						foreach (var typeInfo in typeGroup)
						{
							var relative = GetPermalink(typeInfo.Path);
							var safeRelative = GetSafeName(relative);
							if (PermalinkPretty)
								safeRelative += "Type";
							var rel = MakeRelative(context.PageLocation, $"{GetNamespaceUriName(group.Namespace)}/{safeRelative}");
							var typeText = GetShortSignatureMarkdown(typeInfo.ShortSignature, rel);
							var summaryText = GetShortSummaryMarkdown(xmlDocFile, typeInfo.TypeInfo, context);
							writer.WriteLine($"| {typeText} | {summaryText} |");
						}
					}

					writer.WriteLine();
					writer.WriteLine(GetCodeGenComment(assemblyFileName));
				});
			}

			foreach (var visibleTypeRecord in visibleTypeRecords)
			{
				if (visibleTypeRecord.Namespace == group.Namespace)
				{
					var relative = GetPermalink(visibleTypeRecord.Path);
					var safeRelative = GetSafeName(relative);
					if (PermalinkPretty)
						safeRelative += "Type.md";
					var typePage = $"{GetNamespaceUriName(visibleTypeRecord.Namespace)}/{safeRelative}";
					yield return WriteMemberPage(
						path: typePage,
						title: GetFullMemberName(visibleTypeRecord.TypeInfo),
						parent: parentPageLocation,
						memberInfo: visibleTypeRecord.TypeInfo,
						context: parentContext);

					var typeKind = GetTypeKind(visibleTypeRecord.TypeInfo);
					if (typeKind is TypeKind.Record or TypeKind.Class or TypeKind.Struct or TypeKind.Interface)
					{
						var memberGroups = visibleTypeRecord.TypeInfo
							.DeclaredMembers
							.Where(x => !(x is TypeInfo) && IsVisible(x))
							.GroupBy(GetMemberUriName)
							.Select(tg => new
							{
								MemberUriName = tg.Key,
								Members = OrderMembers(tg, x => x).ToList(),
							})
							.ToList();

						foreach (var memberGroup in memberGroups)
						{
							yield return WriteMemberPage(
								path: $"{GetNamespaceUriName(visibleTypeRecord.Namespace)}/{GetTypeUriName(visibleTypeRecord.TypeInfo)}/{memberGroup.MemberUriName}.md",
								parent: typePage,
								title: memberGroup.MemberUriName,
								memberGroup: memberGroup.Members,
								context: context);
						}
					}
				}
			}
		}
	}

	private string? GetFrontMatter(string title, string relativeLink)
	{
		if (string.IsNullOrEmpty(FrontMatter))
			return null;

		var contents = File.ReadAllText(FrontMatter);
		return contents.Replace("$title", title, StringComparison.Ordinal).Replace("$ref", relativeLink, StringComparison.Ordinal);
	}

	private NamedText CreateNamedText(string name, Action<MarkdownWriter> writeTo)
	{
		using var stringWriter = new StringWriter();
		if (NewLine is not null)
			stringWriter.NewLine = NewLine;

		var code = new MarkdownWriter(stringWriter);
		writeTo(code);
		return new NamedText(name, stringWriter.ToString());
	}

	private static Collection<XmlDocBlock>? GetSummary(XmlDocFile xmlDocFile, MemberInfo member) =>
		GetSummary(xmlDocFile.FindMember(XmlDocUtility.GetXmlDocRef(member)), member);

	private static Collection<XmlDocBlock>? GetSummary(XmlDocMember? xmlDocMember, MemberInfo member)
	{
		var summary = xmlDocMember?.Summary;

		if (summary is null || summary.Count == 0)
		{
			var constructorInfo = member as ConstructorInfo;
			if (constructorInfo is not null && !constructorInfo.IsStatic && constructorInfo.GetParameters().Length == 0)
				summary = new Collection<XmlDocBlock> { new() { Inlines = { new XmlDocInline { Text = "The default constructor." } } } };
		}

		return summary;
	}

	private string GetShortSummaryMarkdown(XmlDocFile xmlDocFile, MemberInfo member, MarkdownContext context) =>
		ToMarkdown(GetSummary(xmlDocFile, member)?.FirstOrDefault()?.Inlines, context) ?? "";

	private static string GetAssemblyUriName(Assembly assembly) => assembly.GetName().Name ?? "";

	private static string GetNamespaceUriName(string? namespaceName) => namespaceName ?? "global";

	private static string GetTypeUriName(TypeInfo typeInfo)
	{
		return GetFullTypeName(typeInfo, x =>
		{
			var genericTypeCount = x.GenericTypeParameters.Length;
			return GetShortName(x) + (genericTypeCount == 0 ? "" : $"-{genericTypeCount}");
		});
	}

	private string GetSafeTypeUriName(TypeInfo typeInfo)
	{
		var name = GetSafeName(GetTypeUriName(typeInfo));
		if (PermalinkPretty)
		{
			// Jekyll doesn't allow "Foo.md" and a folder named "Foo" containing the method markdown files.
			// So we rename the type "FooType.md" to avoid this conflict.
			name += "Type";
		}
		return name;
	}

	private string GetSafeName(string name)
	{
		if (PermalinkPretty)
			return name.Replace(".", "", StringComparison.Ordinal); // Jekyll can't handle dots in file name.

		return name;
	}

	private string GetMemberUriName(MemberInfo memberInfo) =>
		memberInfo is TypeInfo typeInfo ? GetSafeTypeUriName(typeInfo) : GetShortName(memberInfo);

	private static string GetShortSignatureMarkdown(ShortSignature shortSignature, string path) =>
		EscapeHtml($"{shortSignature.Prefix}[{shortSignature.Name}]({path}){shortSignature.Suffix}");

	private static string EscapeHtml(string value) =>
		value.Replace("&", "&amp;", StringComparison.Ordinal).Replace("<", "&lt;", StringComparison.Ordinal).Replace(">", "&gt;", StringComparison.Ordinal).Replace("|", "&#x7C;", StringComparison.Ordinal);

	private static string SurroundCode(string value)
	{
		var backticks = new string('`', Regex.Matches(value, "`+").Select(x => x.Length).Concat([0]).Max() + 1);
		return backticks + value + backticks;
	}

	private NamedText WriteMemberPage(string path, string parent, string title, MemberInfo memberInfo, MarkdownContext context) =>
		WriteMemberPage(path, parent, title, [memberInfo], context);

	private string GetFileExtension() => PermalinkPretty ? "" : ".md";

	private string GetPermalink(string path)
	{
		if (PermalinkPretty)
		{
			// permalinks paths cannot end in .md
			var pos = path.LastIndexOf('.');
			if (pos > 0)
				path = path.Substring(0, pos);
		}
		return path.Replace("\\", "/", StringComparison.Ordinal);
	}

	private NamedText WriteMemberPage(string path, string parent, string title, List<MemberInfo> memberGroup, MarkdownContext context)
	{
		var extension = GetFileExtension();

		return CreateNamedText(path, writer =>
		{
			var relative = GetPermalink(path);
			var front = GetFrontMatter(title, relative);
			if (!string.IsNullOrEmpty(front))
				writer.WriteLine(front!);

			for (var memberIndex = 0; memberIndex < memberGroup.Count; memberIndex++)
			{
				var memberInfo = memberGroup[memberIndex];
				var memberContext = new MarkdownContext(context, memberInfo, path);
				var typeInfo = memberInfo as TypeInfo;
				var typeKind = typeInfo is null ? default(TypeKind?) : GetTypeKind(typeInfo);

				if (memberIndex != 0)
					writer.WriteLine();

				writer.WriteLine($"# {EscapeHtml(GetMemberHeading(memberGroup, memberIndex))}");

				var xmlDocRef = XmlDocUtility.GetXmlDocRef(memberInfo);
				var xmlDocMember = memberContext.XmlDocFile.FindMember(xmlDocRef);

				var summary = GetSummary(xmlDocMember, memberInfo);
				if (summary is not null && summary.Count != 0)
				{
					writer.WriteLine();
					writer.WriteLines(ToMarkdown(summary, memberContext));
				}

				var seeAlsoMembers = new List<MemberInfo>();
				if (xmlDocMember is not null)
				{
					foreach (var seeAlsoInfo in xmlDocMember.SeeAlso)
					{
						var xmlDocName = seeAlsoInfo.Ref;
						if (xmlDocName is not null && memberContext.MembersByXmlDocName.TryGetValue(xmlDocName, out var seeAlsoMember))
							seeAlsoMembers.Add(seeAlsoMember);
					}
				}

				writer.WriteLine();
				writer.WriteLine("```csharp");
				writer.WriteLine(GetFullSignature(memberInfo, seeAlsoMembers));
				writer.WriteLine("```");

				if (xmlDocMember is not null)
				{
					var typeParameters = xmlDocMember.TypeParameters;
					var parameters = xmlDocMember.Parameters;

					// record parameters are documented by the constructor, so don't repeat them here
					if (typeKind == TypeKind.Record)
						parameters = new Collection<XmlDocParameter>();

					if (typeParameters.Count + parameters.Count > 0)
					{
						writer.WriteLine();
						writer.WriteLine("| parameter | description |");
						writer.WriteLine("| --- | --- |");
						foreach (var typeParameter in typeParameters)
						{
							var description = ToMarkdown(typeParameter.Description.FirstOrDefault()?.Inlines, memberContext) ?? "";
							writer.WriteLine($"| {typeParameter.Name} | {description} |");
						}
						foreach (var parameter in parameters)
						{
							var description = ToMarkdown(parameter.Description.FirstOrDefault()?.Inlines, memberContext) ?? "";
							writer.WriteLine($"| {parameter.Name} | {description} |");
						}
					}
				}

				if (typeKind == TypeKind.Enum)
				{
					writer.WriteLine();
					writer.WriteLine("## Values");
					writer.WriteLine();
					writer.WriteLine("| name | value | description |");
					writer.WriteLine("| --- | --- | --- |");

					var isFlags = IsFlagsEnum(typeInfo!);
					foreach (var enumValue in typeInfo!.DeclaredMembers.OfType<FieldInfo>().Where(x => x.IsPublic && x.IsLiteral))
					{
						var valueObject = enumValue.GetValue(null);
						var valueText = isFlags ? "0x" + Convert.ToString(Convert.ToInt64(valueObject, CultureInfo.InvariantCulture), 16).ToUpperInvariant() :
							Enum.GetUnderlyingType(typeInfo.AsType()) == typeof(ulong) ? Convert.ToString(Convert.ToUInt64(valueObject, CultureInfo.InvariantCulture), CultureInfo.InvariantCulture) :
							Convert.ToString(Convert.ToInt64(valueObject, CultureInfo.InvariantCulture), CultureInfo.InvariantCulture);
						var description = GetShortSummaryMarkdown(memberContext.XmlDocFile, enumValue, memberContext);
						writer.WriteLine($"| {enumValue.Name} | {SurroundCode(valueText)} | {description} |");
					}
				}
				else if (typeKind is TypeKind.Record or TypeKind.Class or TypeKind.Struct or TypeKind.Interface)
				{
					var innerMemberVisibilityGroups = typeInfo!
						.DeclaredMembers
						.Where(IsVisible)
						.GroupBy(GetVisibility)
						.Select(tg => new
						{
							Visibility = tg.Key,
							Members = tg.ToList(),
						})
						.OrderByDescending(x => (int) x.Visibility);
					foreach (var innerMemberVisibilityGroup in innerMemberVisibilityGroups)
					{
						var innerMemberSignatureGroups = OrderMembers(innerMemberVisibilityGroup
							.Members
							.GroupBy(x => GetShortSignature(x))
							.Select(tg => new
							{
								ShortSignature = tg.Key,
								Members = tg.OrderBy(x => (x as TypeInfo)?.GenericTypeParameters.Length ?? 0).ToList(),
							}), x => x.Members[0]).ToList();

						if (innerMemberSignatureGroups.Count != 0)
						{
							writer.WriteLine();
							switch (innerMemberVisibilityGroup.Visibility)
							{
								case XmlDocVisibilityLevel.Public:
									writer.WriteLine(typeKind == TypeKind.Interface ? "## Members" : "## Public Members");
									break;
								case XmlDocVisibilityLevel.Protected:
									writer.WriteLine("## Protected Members");
									break;
								case XmlDocVisibilityLevel.Internal:
									writer.WriteLine("## Internal Members");
									break;
								case XmlDocVisibilityLevel.Private:
									writer.WriteLine("## Private Members");
									break;
								default:
									throw new InvalidOperationException();
							}
							writer.WriteLine();
							writer.WriteLine("| name | description |");
							writer.WriteLine("| --- | --- |");

							foreach (var innerMemberGroup in innerMemberSignatureGroups)
							{
								var innerMembers = innerMemberGroup.Members;
								var firstInnerMember = innerMembers[0];
								var memberPath = firstInnerMember is TypeInfo ?
									$"{GetMemberUriName(firstInnerMember)}{extension}" :
									$"{GetTypeUriName(typeInfo)}/{GetMemberUriName(firstInnerMember)}{extension}";
								var memberText = GetShortSignatureMarkdown(innerMemberGroup.ShortSignature, memberPath);
								var summaryText = GetShortSummaryMarkdown(memberContext.XmlDocFile, firstInnerMember, memberContext);
								if (innerMembers.Count != 1)
									summaryText += $" ({innerMembers.Count} {GetMemberGroupNoun(innerMembers)})";

								writer.WriteLine($"| {memberText} | {summaryText} |");
							}
						}
					}
				}

				var returnValue = xmlDocMember?.ReturnValue;
				if (returnValue is not null && returnValue.Count != 0)
				{
					writer.WriteLine();
					writer.WriteLine("## Return Value");
					writer.WriteLine();
					writer.WriteLines(ToMarkdown(returnValue, memberContext));
				}

				var propertyValue = xmlDocMember?.PropertyValue;
				if (propertyValue is not null && propertyValue.Count != 0)
				{
					writer.WriteLine();
					writer.WriteLine("## Property Value");
					writer.WriteLine();
					writer.WriteLines(ToMarkdown(propertyValue, memberContext));
				}

				var exceptions = xmlDocMember?.Exceptions;
				if (exceptions is not null && exceptions.Count != 0)
				{
					writer.WriteLine();
					writer.WriteLine("## Exceptions");
					writer.WriteLine();
					writer.WriteLine("| exception | condition |");
					writer.WriteLine("| --- | --- |");

					foreach (var exception in exceptions)
					{
						MemberInfo? exceptionMemberInfo = null;
						if (exception.ExceptionTypeRef is not null)
							memberContext.MembersByXmlDocName.TryGetValue(exception.ExceptionTypeRef, out exceptionMemberInfo);
						var text = exceptionMemberInfo is not null ? GetShortName(exceptionMemberInfo) : exception.ExceptionTypeRef is not null ? XmlDocUtility.GetShortNameForXmlDocRef(exception.ExceptionTypeRef) : "";
						var link = WrapMarkdownRefLink(text, exceptionMemberInfo, memberContext);
						writer.WriteLine($"| {link} | {ToMarkdown(exception.Condition.FirstOrDefault()?.Inlines, memberContext) ?? ""} |");
					}
				}

				var remarks = xmlDocMember?.Remarks;
				if (remarks is not null && remarks.Count != 0)
				{
					writer.WriteLine();
					writer.WriteLine("## Remarks");
					writer.WriteLine();
					writer.WriteLines(ToMarkdown(remarks, memberContext));
				}

				var examples = xmlDocMember?.Examples;
				if (examples is not null && examples.Count != 0)
				{
					writer.WriteLine();
					writer.WriteLine("## Examples");
					writer.WriteLine();
					writer.WriteLines(ToMarkdown(examples, memberContext));
				}

				writer.WriteLine();
				writer.WriteLine("## See Also");
				writer.WriteLine();

				var declaringType = memberInfo.DeclaringType?.GetTypeInfo();
				var declaringTypeXmlDocName = declaringType is null ? null : XmlDocUtility.GetXmlDocRef(declaringType);
				if (declaringType is not null)
					seeAlsoMembers.Add(declaringType);

				foreach (var seeAlso in seeAlsoMembers
					.Where(x => XmlDocUtility.GetXmlDocRef(x) != xmlDocRef)
					.Select(GetGenericDefinition)
					.GroupBy(XmlDocUtility.GetXmlDocRef)
					.Select(x => new { Member = x.First(), XmlDocName = x.Key! })
					.OrderBy(x => x.XmlDocName == declaringTypeXmlDocName))
				{
					if (memberContext.MembersByXmlDocName.ContainsKey(seeAlso.XmlDocName!) ||
						FindExternalDocumentation(seeAlso.Member) is not null)
					{
						var shortSignature = GetShortSignature(seeAlso.Member, forSeeAlso: true);
						writer.WriteLine("* " + shortSignature.Prefix +
							WrapMarkdownRefLink(shortSignature.Name, seeAlso.Member, memberContext) + shortSignature.Suffix);
					}
				}

				if (NamespacePages)
				{
					var namespacePath = GetPermalink(MakeRelative(path, parent));
					writer.WriteLine("* " + $"namespace\u00A0[{GetNamespaceName(declaringType ?? typeInfo!)}]({namespacePath}{extension})");

					var assemblyName = (declaringType ?? typeInfo!).Assembly.GetName().Name;
					var assemblyPath = GetPermalink(MakeRelative(path, RootPageLocation!));
					writer.WriteLine("* " + $"assembly\u00A0[{assemblyName}]({assemblyPath})");
				}
				else
				{
					writer.WriteLine("* " + $"namespace\u00A0[{GetNamespaceName(declaringType ?? typeInfo!)}](../{(typeInfo is not null ? "" : "../")}{GetAssemblyUriName((declaringType ?? typeInfo!).Assembly)}{extension})");
				}

				if (memberIndex < memberGroup.Count - 1)
				{
					writer.WriteLine();
					writer.WriteLine("---");
				}
			}

			writer.WriteLine();
			writer.WriteLine(GetCodeGenComment(context.AssemblyFileName));
		});
	}

	private ExternalDocumentation? FindExternalDocumentation(MemberInfo? memberInfo)
	{
		if (memberInfo is null)
			return null;

		var namespaceName = (memberInfo as TypeInfo ?? memberInfo.DeclaringType!.GetTypeInfo()).Namespace;
		return ExternalDocs?.FirstOrDefault(x => x.Namespace == namespaceName);
	}

	private MemberInfo GetGenericDefinition(MemberInfo memberInfo)
	{
		if (memberInfo is TypeInfo typeInfo)
			return typeInfo.IsGenericType ? typeInfo.GetGenericTypeDefinition().GetTypeInfo() : typeInfo;

		if (memberInfo is MethodInfo methodInfo)
			return methodInfo.IsGenericMethod ? methodInfo.GetGenericMethodDefinition() : methodInfo;

		return memberInfo;
	}

	private bool IsVisible(MemberInfo memberInfo)
	{
		if (IsBuiltInRecordMember(memberInfo))
			return false;

		var visibility = GetVisibility(memberInfo);
		if (IsMorePrivateThan(visibility, Visibility))
			return false;

		if (!IncludeObsolete && memberInfo.GetCustomAttributes<ObsoleteAttribute>().Any())
			return false;

		if (SkipUnbrowsable && memberInfo.GetCustomAttributes<EditorBrowsableAttribute>().Any(x => x.State == EditorBrowsableState.Never))
			return false;

		if (SkipCompilerGenerated && memberInfo.GetCustomAttributes<CompilerGeneratedAttribute>().Any())
			return false;

		var name = memberInfo.Name;
		if (name.Length == 0 || name[0] == '<')
			return false;

		// nested types of invisible types are invisible
		if (memberInfo.DeclaringType is { } declaringType && !IsVisible(declaringType))
			return false;

		if (memberInfo is TypeInfo)
			return true;

		if (memberInfo is not MethodBase methodBase)
			return true;

		if (memberInfo is ConstructorInfo)
			return true;

		if (!methodBase.IsSpecialName)
			return true;

		if (methodBase.Name.StartsWith("op_", StringComparison.Ordinal))
			return true;

		return false;
	}

	private static bool IsMorePrivateThan(XmlDocVisibilityLevel visibility1, XmlDocVisibilityLevel visibility2) => (int) visibility1 < (int) visibility2;

	public static XmlDocVisibilityLevel GetMostPublic(params XmlDocVisibilityLevel[] visibilityLevels) => (XmlDocVisibilityLevel) visibilityLevels.Max(x => (int) x);

	public static XmlDocVisibilityLevel GetMostPrivate(params XmlDocVisibilityLevel[] visibilityLevels) => (XmlDocVisibilityLevel) visibilityLevels.Min(x => (int) x);

	private static string GetMemberHeading(List<MemberInfo> membersInfos, int index)
	{
		var heading = $"{GetFullMemberName(membersInfos[index])} {GetMemberGroupNoun([membersInfos[index]])}";
		if (membersInfos.Count > 1)
			heading += $" ({index + 1} of {membersInfos.Count})";
		return heading;
	}

	private static string GetMemberGroupNoun(List<MemberInfo> memberInfos)
	{
		var plural = memberInfos.Count != 1;

		if (memberInfos.All(x => x is ConstructorInfo))
			return plural ? "constructors" : "constructor";
		if (memberInfos.All(x => (x as PropertyInfo)?.GetIndexParameters().Length > 0))
			return plural ? "indexers" : "indexer";
		if (memberInfos.All(x => x is PropertyInfo))
			return plural ? "properties" : "property";
		if (memberInfos.All(x => (x as MethodInfo)?.Name.StartsWith("op_", StringComparison.Ordinal) == true))
			return plural ? "operators" : "operator";
		if (memberInfos.All(x => x is MethodInfo))
			return plural ? "methods" : "method";
		if (memberInfos.All(x => x is EventInfo))
			return plural ? "events" : "event";
		if (memberInfos.All(x => x is FieldInfo))
			return plural ? "fields" : "field";
		if (memberInfos.All(x => x is TypeInfo))
			return GetTypeGroupNoun([.. memberInfos.Cast<TypeInfo>()]);
		return plural ? "members" : "member";
	}

	private static string GetTypeGroupNoun(List<TypeInfo> typeInfos)
	{
		var plural = typeInfos.Count != 1;

		var typeKinds = typeInfos.Select(GetTypeKind).ToList();
		if (typeKinds.All(x => x == TypeKind.Record))
			return plural ? "records" : "record";
		if (typeKinds.All(x => x == TypeKind.Class))
			return plural ? "classes" : "class";
		if (typeKinds.All(x => x == TypeKind.Interface))
			return plural ? "interfaces" : "interface";
		if (typeKinds.All(x => x == TypeKind.Struct))
			return plural ? "structures" : "structure";
		if (typeKinds.All(x => x == TypeKind.Enum))
			return plural ? "enumerations" : "enumeration";
		if (typeKinds.All(x => x == TypeKind.Delegate))
			return plural ? "delegates" : "delegate";
		return plural ? "types" : "type";
	}

	private static string GetNamespaceName(TypeInfo typeInfo) => typeInfo.Namespace ?? "global";

	private static string GetShortName(MemberInfo memberInfo)
	{
		var name = memberInfo.Name;

		var tickIndex = name.IndexOf('`', StringComparison.Ordinal);
		if (tickIndex != -1)
			name = name[..tickIndex];

		if (name is ".ctor" or ".cctor")
			name = GetShortName(memberInfo.DeclaringType!.GetTypeInfo());
		else if (name == "op_UnaryPlus")
			name = "op_Addition";
		else if (name == "op_UnaryNegation")
			name = "op_Subtraction";

		return name;
	}

	private static string GetOperatorKeywordName(string name) =>
		name switch
		{
			"op_Addition" => "operator +",
			"op_BitwiseAnd" => "operator &",
			"op_BitwiseOr" => "operator |",
			"op_Decrement" => "operator --",
			"op_Division" => "operator /",
			"op_Equality" => "operator ==",
			"op_ExclusiveOr" => "operator ^",
			"op_Explicit" => "explicit operator",
			"op_False" => "operator false",
			"op_GreaterThan" => "operator >",
			"op_GreaterThanOrEqual" => "operator >=",
			"op_Implicit" => "implicit operator",
			"op_Increment" => "operator ++",
			"op_Inequality" => "operator !=",
			"op_LeftShift" => "operator <<",
			"op_LessThan" => "operator <",
			"op_LessThanOrEqual" => "operator <=",
			"op_LogicalNot" => "operator !",
			"op_Modulus" => "operator %",
			"op_Multiply" => "operator *",
			"op_OnesComplement" => "operator ~",
			"op_RightShift" => "operator >>",
			"op_Subtraction" => "operator -",
			"op_True" => "operator true",
			"op_UnaryNegation" => "operator -",
			"op_UnaryPlus" => "operator +",
			_ => name,
		};

	private static string GetFullMemberName(MemberInfo memberInfo)
	{
		if (memberInfo is TypeInfo type)
			return GetFullTypeName(type, t => GetShortName(t) + RenderShortGenericParameters(t.GenericTypeParameters));

		if (memberInfo is ConstructorInfo || (memberInfo as PropertyInfo)?.GetIndexParameters().Length > 0)
			return GetFullTypeName(memberInfo.DeclaringType!.GetTypeInfo(), t => GetShortName(t) + RenderShortGenericParameters(t.GenericTypeParameters));

		var methodName = (memberInfo as MethodInfo)?.Name;
		if (methodName?.StartsWith("op_", StringComparison.Ordinal) == true)
			return string.Concat(GetFullTypeName(memberInfo.DeclaringType!.GetTypeInfo(), t => GetShortName(t) + RenderShortGenericParameters(t.GenericTypeParameters)), " ", methodName.AsSpan(3));

		return GetFullTypeName(memberInfo.DeclaringType!.GetTypeInfo(), t => GetShortName(t) + RenderShortGenericParameters(t.GenericTypeParameters)) + "." +
			GetShortName(memberInfo) + RenderShortGenericParameters(GetGenericArguments(memberInfo));
	}

	private static string GetFullTypeName(TypeInfo typeInfo, Func<TypeInfo, string> render)
	{
		var name = render(typeInfo);
		if (typeInfo.DeclaringType is not null)
			name = $"{GetFullTypeName(typeInfo.DeclaringType.GetTypeInfo(), render)}.{name}";
		return name;
	}

	private sealed record ShortSignature(string Prefix, string Name, string Suffix);

	private ShortSignature GetShortSignature(MemberInfo memberInfo, bool forSeeAlso = false)
	{
		var name = GetOperatorKeywordName(GetShortName(memberInfo));
		var prefix = "";
		var suffix = "";

		if (memberInfo is TypeInfo typeInfo)
		{
			name += RenderShortGenericParameters(typeInfo.GenericTypeParameters);

			prefix = GetTypeKind(typeInfo) switch
			{
				TypeKind.Record => "record ",
				TypeKind.Class => "class ",
				TypeKind.Interface => "interface ",
				TypeKind.Struct => "struct ",
				TypeKind.Enum => "enum ",
				TypeKind.Delegate => "delegate ",
				_ => prefix,
			};

			if (!forSeeAlso)
			{
				if (IsFlagsEnum(typeInfo))
					prefix = "[Flags] " + prefix;
				if (IsStatic(typeInfo))
					prefix = "static " + prefix;
				else if (IsAbstract(typeInfo))
					prefix = "abstract " + prefix;
				else if (IsVirtual(typeInfo))
					prefix = "virtual " + prefix;
				else if (IsOverride(typeInfo))
					prefix = "override " + prefix;
			}
		}
		else if (memberInfo is EventInfo eventInfo)
		{
			prefix = "event ";
			if (!forSeeAlso)
			{
				if (IsStatic(eventInfo))
					prefix = "static " + prefix;
				else if (IsAbstract(eventInfo))
					prefix = "abstract " + prefix;
				else if (IsVirtual(eventInfo))
					prefix = "virtual " + prefix;
				else if (IsOverride(eventInfo))
					prefix = "override " + prefix;
			}
		}
		else if (memberInfo is PropertyInfo propertyInfo)
		{
			if (!forSeeAlso)
				suffix = GetPropertyGetSet(propertyInfo);

			if (forSeeAlso)
				prefix = "property ";
			else if (IsStatic(propertyInfo))
				prefix = "static ";
			else if (IsAbstract(propertyInfo))
				prefix = "abstract ";
			else if (IsVirtual(propertyInfo))
				prefix = "virtual ";
			else if (IsOverride(propertyInfo))
				prefix = "override ";
		}
		else if (memberInfo is FieldInfo fieldInfo)
		{
			if (forSeeAlso)
			{
				prefix = "field ";
			}
			else
			{
				if (IsConst(fieldInfo))
					prefix += "const ";
				if (IsStatic(fieldInfo))
					prefix = "static ";
				if (IsReadOnly(fieldInfo))
					prefix += "readonly ";
			}
		}
		else if (memberInfo is MethodBase methodBase)
		{
			var isOperator = methodBase.Name.StartsWith("op_", StringComparison.Ordinal);

			if (methodBase is MethodInfo)
				name += RenderShortGenericParameters(methodBase.GetGenericArguments());

			if (!forSeeAlso && !isOperator)
				suffix += methodBase.GetParameters().Length == 0 ? "()" : "(…)";

			if (forSeeAlso)
				prefix = "method ";
			else if (IsStatic(methodBase) && !isOperator)
				prefix = "static " + prefix;
			else if (IsAbstract(methodBase))
				prefix = "abstract " + prefix;
			else if (IsVirtual(methodBase))
				prefix = "virtual " + prefix;
			else if (IsOverride(methodBase))
				prefix = "override " + prefix;
		}

		return new ShortSignature(Prefix: prefix.Replace(' ', '\u00A0'), Name: name, Suffix: suffix.Replace(' ', '\u00A0'));
	}

	private string GetPropertyGetSet(PropertyInfo propertyInfo)
	{
		var getMethod = propertyInfo.GetMethod;
		var setMethod = propertyInfo.SetMethod;
		if (getMethod is null && setMethod is null)
			throw new InvalidOperationException();

		var getVisibility = getMethod is null ? XmlDocVisibilityLevel.Private : GetMethodVisibility(getMethod);
		var setVisibility = setMethod is null ? XmlDocVisibilityLevel.Private : GetMethodVisibility(setMethod);

		if (getMethod is not null && (setMethod is null || IsMorePrivateThan(setVisibility, Visibility)))
			return " { get; }";
		if (getMethod is null || IsMorePrivateThan(getVisibility, Visibility))
			return " { set; }";

		if (getVisibility == setVisibility)
			return " { get; set; }";
		if (IsMorePrivateThan(getVisibility, setVisibility))
			return $" {{ {GetAccessModifier(getMethod)} get; set; }}";
		return $" {{ get; {GetAccessModifier(setMethod!)} set; }}";
	}

	private string GetFullSignature(MemberInfo memberInfo, ICollection<MemberInfo> seeAlsoMembers)
	{
		var stringBuilder = new StringBuilder();
		var lineBuilder = new StringBuilder();
		var segmentBuilder = new StringBuilder();
		const int maxLineLength = 100;

		void WrapLineIfNecessary(bool hard)
		{
			const string indent = "    ";

			if (lineBuilder.Length > indent.Length && (hard || lineBuilder.Length + segmentBuilder.Length > maxLineLength))
			{
				lineBuilder.Append(ActualNewLine);
				stringBuilder.Append(lineBuilder);
				lineBuilder.Clear();

				if (!hard)
					lineBuilder.Append(indent);
			}
		}

		foreach (var part in GetFullSignatureParts(memberInfo, seeAlsoMembers))
		{
			if (part.Length == 0 || part == ActualNewLine)
			{
				WrapLineIfNecessary(false);

				lineBuilder.Append(segmentBuilder);
				segmentBuilder.Clear();

				WrapLineIfNecessary(part == ActualNewLine);
			}
			else
			{
				segmentBuilder.Append(part);
			}
		}

		WrapLineIfNecessary(false);

		lineBuilder.Append(segmentBuilder);
		stringBuilder.Append(lineBuilder);
		return stringBuilder.ToString();
	}

	private IEnumerable<string> GetFullSignatureParts(MemberInfo memberInfo, ICollection<MemberInfo> seeAlsoMembers)
	{
		var typeInfo = memberInfo as TypeInfo;
		var typeKind = typeInfo is null ? default(TypeKind?) : GetTypeKind(typeInfo);

		var obsoleteAttribute = memberInfo.GetCustomAttribute<ObsoleteAttribute>();
		if (obsoleteAttribute is not null)
		{
			var message = obsoleteAttribute.Message;
			if (string.IsNullOrWhiteSpace(message))
			{
				yield return "[Obsolete]";
			}
			else
			{
				yield return "[Obsolete(";
				yield return RenderConstant(message);
				yield return ")]";
			}
			yield return ActualNewLine;
		}

		var browsableAttribute = memberInfo.GetCustomAttribute<EditorBrowsableAttribute>();
		if (browsableAttribute is not null && browsableAttribute.State != EditorBrowsableState.Always)
		{
			yield return "[EditorBrowsable(";
			yield return RenderConstant(browsableAttribute.State);
			yield return ")]";
			yield return ActualNewLine;
		}

		var attributeUsage = memberInfo.GetCustomAttribute<AttributeUsageAttribute>();
		if (attributeUsage is not null)
		{
			yield return "[AttributeUsage(";

			yield return RenderConstant(attributeUsage.ValidOn);

			if (!attributeUsage.Inherited)
			{
				yield return ", ";
				yield return "";
				yield return "Inherited = false";
			}

			if (attributeUsage.AllowMultiple)
			{
				yield return ", ";
				yield return "";
				yield return "AllowMultiple = true";
			}

			yield return ")]";
			yield return ActualNewLine;
		}

		if (IsFlagsEnum(memberInfo))
		{
			yield return "[Flags]";
			yield return ActualNewLine;
		}

		yield return $"{GetAccessModifier(memberInfo)} ";

		if (IsStatic(memberInfo))
			yield return "static ";
		else if (typeKind == TypeKind.Class && typeInfo!.IsSealed)
			yield return "sealed ";
		else if (IsAbstract(memberInfo))
			yield return "abstract ";
		else if (IsVirtual(memberInfo))
			yield return "virtual ";
		else if (IsOverride(memberInfo))
			yield return "override ";

		if (IsConst(memberInfo))
			yield return "const ";
		if (IsReadOnly(memberInfo))
			yield return "readonly ";

		if (memberInfo is EventInfo)
			yield return "event ";

		switch (typeKind)
		{
			case TypeKind.Record:
				yield return "record ";
				break;
			case TypeKind.Class:
				yield return "class ";
				break;
			case TypeKind.Interface:
				yield return "interface ";
				break;
			case TypeKind.Struct:
				yield return "struct ";
				break;
			case TypeKind.Enum:
				yield return "enum ";
				break;
			case TypeKind.Delegate:
				yield return "delegate ";
				break;
		}

		var shortName = GetOperatorKeywordName(GetShortName(memberInfo));
		if (shortName == "Item" && memberInfo is PropertyInfo)
			shortName = "this";

		var isConversion = shortName is "explicit operator" or "implicit operator";

		var nullableContextFlags = GetNullableContextFlags(memberInfo.GetCustomAttributes());
		if (nullableContextFlags.Length == 0)
		{
			var ancestor = memberInfo;
			while (true)
			{
				ancestor = ancestor.DeclaringType?.GetTypeInfo();
				if (ancestor is null)
					break;
				nullableContextFlags = GetNullableContextFlags(ancestor.GetCustomAttributes());
				if (nullableContextFlags.Length != 0)
					break;
			}
		}

		var (valueType, valueAttributes) = GetValueType(memberInfo);
		if (valueType is not null && !isConversion)
		{
			yield return RenderTypeName(valueType, seeAlsoMembers, valueAttributes, nullableContextFlags);
			yield return " ";
		}

		if (valueType is not null && isConversion)
		{
			yield return shortName;
			yield return " ";
			yield return RenderTypeName(valueType, seeAlsoMembers, valueAttributes, nullableContextFlags);
		}
		else
		{
			yield return "";
			yield return shortName;
		}

		var genericParameters = GetGenericArguments(memberInfo);
		if (genericParameters.Length != 0)
			yield return RenderGenericParameters(genericParameters);

		if (typeKind is TypeKind.Record or TypeKind.Class or TypeKind.Struct or TypeKind.Interface)
		{
			var isFirstBase = true;
			if (typeKind == TypeKind.Class && typeInfo!.BaseType != typeof(object))
			{
				yield return " : ";
				yield return "";
				yield return RenderTypeName(typeInfo.BaseType!.GetTypeInfo(), seeAlsoMembers);
				isFirstBase = false;
			}

			var baseInterfaces = typeInfo!.ImplementedInterfaces.Select(x => x.GetTypeInfo())
				.Where(x => x.IsPublic)
				.OrderBy(x => x.Name, StringComparer.OrdinalIgnoreCase)
				.ThenBy(x => x.IsGenericType ? x.GenericTypeArguments.Length : 0)
				.ThenBy(x => x.IsGenericType ? RenderGenericArguments(x.GenericTypeArguments) : "", StringComparer.OrdinalIgnoreCase)
				.ToList();
			var baseTypeInterfaces = typeInfo.BaseType?.GetTypeInfo().ImplementedInterfaces.Select(x => x.GetTypeInfo()).ToList();
			foreach (var baseInterface in baseInterfaces)
			{
				if (!(typeKind == TypeKind.Class && baseTypeInterfaces!.Contains(baseInterface)) &&
					!baseInterfaces.Any(x => XmlDocUtility.GetXmlDocRef(x) != XmlDocUtility.GetXmlDocRef(baseInterface) && IsLessDerived(baseInterface, x)) &&
					!(typeKind == TypeKind.Record && baseInterface.Name == "IEquatable`1" && baseInterface.GenericTypeArguments[0] == typeInfo.AsType()))
				{
					yield return isFirstBase ? " : " : ", ";
					yield return "";
					yield return RenderTypeName(baseInterface, seeAlsoMembers);
					isFirstBase = false;
				}
			}
		}

		if (typeKind == TypeKind.Enum && Enum.GetUnderlyingType(typeInfo!.AsType()) != typeof(int))
		{
			yield return " : ";
			yield return RenderTypeName(Enum.GetUnderlyingType(typeInfo.AsType()).GetTypeInfo(), seeAlsoMembers);
		}

		ParameterInfo[]? parameterInfos = null;

		var propertyInfo = memberInfo as PropertyInfo;
		if (propertyInfo is not null)
		{
			parameterInfos = GetParameters(propertyInfo);
			if (parameterInfos.Length == 0)
				parameterInfos = null;
		}

		var methodInfo = memberInfo as MethodBase ?? TryGetDelegateInvoke(memberInfo);
		if (methodInfo is not null)
			parameterInfos = GetParameters(methodInfo);

		if (parameterInfos is not null)
		{
			yield return propertyInfo is not null ? "[" : "(";
			yield return "";

			var isFirstParameter = true;
			foreach (var (parameterInfo, index) in parameterInfos.Select((x, i) => (x, i)))
			{
				if (!isFirstParameter)
				{
					yield return ", ";
					yield return "";
				}

				if (parameterInfo.GetCustomAttributes<CallerFilePathAttribute>().Any())
					yield return "[CallerFilePath] ";
				if (parameterInfo.GetCustomAttributes<CallerLineNumberAttribute>().Any())
					yield return "[CallerLineNumber] ";
				if (parameterInfo.GetCustomAttributes<CallerMemberNameAttribute>().Any())
					yield return "[CallerMemberName] ";

				if (isFirstParameter && IsStatic(memberInfo) && memberInfo.GetCustomAttributes<ExtensionAttribute>().Any())
					yield return "this ";

				if (parameterInfo.ParameterType.IsByRef)
					yield return parameterInfo.IsOut ? "out " : "ref ";
				if (parameterInfo.GetCustomAttributes<ParamArrayAttribute>().Any())
					yield return "params ";

				yield return RenderTypeName(parameterInfo.ParameterType.GetTypeInfo(),
					seeAlso: seeAlsoMembers,
					attributes: [.. parameterInfo.GetCustomAttributes()],
					nullableContextFlags: nullableContextFlags);

				yield return " ";
				if (IsKeyword(parameterInfo.Name!))
					yield return "@";
				yield return parameterInfo.Name ?? "P_" + index.ToString(CultureInfo.InvariantCulture); // default as per ILSpy if null

				if (ParameterHasDefaultValue(parameterInfo))
				{
					yield return " = ";
					if (CanRenderParameterConstant(parameterInfo))
						yield return RenderConstant(parameterInfo.DefaultValue);
					else if (parameterInfo.ParameterType.GetTypeInfo().IsValueType || parameterInfo.ParameterType.IsGenericParameter)
						yield return "default";
					else
						yield return "null";
				}

				isFirstParameter = false;
			}

			yield return propertyInfo is not null ? "]" : ")";
		}

		if (propertyInfo is not null)
			yield return GetPropertyGetSet(propertyInfo);

		foreach (var genericParameter in genericParameters)
		{
			var isFirstPart = true;

			if (genericParameter.GetTypeInfo().GenericParameterAttributes.HasFlag(GenericParameterAttributes.ReferenceTypeConstraint))
			{
				yield return ActualNewLine;
				yield return $"    where {genericParameter.Name} : ";

				yield return "class";
				isFirstPart = false;
			}

			var isStruct = genericParameter.GetTypeInfo().GenericParameterAttributes.HasFlag(GenericParameterAttributes.NotNullableValueTypeConstraint);
			if (isStruct)
			{
				if (isFirstPart)
				{
					yield return ActualNewLine;
					yield return $"    where {genericParameter.Name} : ";
				}
				else
				{
					yield return ", ";
				}

				yield return "struct";
				isFirstPart = false;
			}

			var genericConstraints = genericParameter.GetTypeInfo().GetGenericParameterConstraints();
			foreach (var genericConstraint in genericConstraints.Where(x => x != typeof(ValueType)))
			{
				if (isFirstPart)
				{
					yield return ActualNewLine;
					yield return $"    where {genericParameter.Name} : ";
				}
				else
				{
					yield return ", ";
				}

				yield return RenderTypeName(genericConstraint.GetTypeInfo(), seeAlsoMembers);
				isFirstPart = false;
			}

			if (!isStruct && genericParameter.GetTypeInfo().GenericParameterAttributes.HasFlag(GenericParameterAttributes.DefaultConstructorConstraint))
			{
				if (isFirstPart)
				{
					yield return ActualNewLine;
					yield return $"    where {genericParameter.Name} : ";
				}
				else
				{
					yield return ", ";
				}

				yield return "new()";
			}
		}

		if (typeKind == TypeKind.Delegate || memberInfo is EventInfo || memberInfo is FieldInfo)
			yield return ";";
	}

	private static (TypeInfo? Type, IReadOnlyList<Attribute>? Attributes) GetValueType(MemberInfo member)
	{
		if (member is EventInfo eventInfo)
			return (eventInfo.EventHandlerType!.GetTypeInfo(), eventInfo.GetCustomAttributes().ToList());

		if (member is PropertyInfo propertyInfo)
			return (propertyInfo.PropertyType.GetTypeInfo(), propertyInfo.GetCustomAttributes().ToList());

		if (member is FieldInfo fieldInfo)
			return (fieldInfo.FieldType.GetTypeInfo(), fieldInfo.GetCustomAttributes().ToList());

		var methodInfo = member as MethodInfo ?? TryGetDelegateInvoke(member);
		if (methodInfo is not null)
			return (methodInfo.ReturnType.GetTypeInfo(), methodInfo.ReturnTypeCustomAttributes.GetCustomAttributes(inherit: false).OfType<Attribute>().ToList());

		return default;
	}

	private static byte[] GetNullableContextFlags(IEnumerable<Attribute> attributes)
	{
		var attribute = attributes.FirstOrDefault(x => x.GetType().FullName == "System.Runtime.CompilerServices.NullableContextAttribute");
		return attribute is null ? [] : [(byte) attribute.GetType().GetField("Flag")!.GetValue(attribute)!];
	}

	private static byte[] GetNullableFlags(IEnumerable<Attribute> attributes)
	{
		var attribute = attributes.FirstOrDefault(x => x.GetType().FullName == "System.Runtime.CompilerServices.NullableAttribute");
		return ((byte[]?) attribute?.GetType().GetField("NullableFlags")!.GetValue(attribute)!) ?? [];
	}

	private static bool ParameterHasDefaultValue(ParameterInfo parameterInfo)
	{
		if (parameterInfo.Attributes.HasFlag(ParameterAttributes.HasDefault))
			return true;

		if (parameterInfo.ParameterType == typeof(decimal) || parameterInfo.ParameterType == typeof(decimal?))
			return parameterInfo.HasDefaultValue;

		return false;
	}

	private static bool CanRenderParameterConstant(ParameterInfo parameterInfo)
	{
		return TryGetBuiltInTypeName(parameterInfo.ParameterType) is not null ||
			TryGetBuiltInTypeName(Nullable.GetUnderlyingType(parameterInfo.ParameterType)) is not null ||
			parameterInfo.ParameterType.GetTypeInfo().IsEnum;
	}

	private static string RenderConstant(object? value)
	{
		if (value is null)
			return "null";

		if (value is bool valueAsBool)
			return valueAsBool ? "true" : "false";

		if (value is char valueAsChar)
			return RenderChar(valueAsChar);

		if (value is string valueAsString)
			return RenderString(valueAsString);

		var type = value.GetType();
		if (type.GetTypeInfo().IsEnum)
		{
			return string.Join(" | ", value.ToString()!
				.Split([", "], StringSplitOptions.None)
				.Select(x => $"{type.Name}.{x}"));
		}

		var rendered = Convert.ToString(value, CultureInfo.InvariantCulture)!;

		if (value is double)
			rendered += "m";

		return rendered;
	}

	private static string RenderString(string value)
	{
		var builder = new StringBuilder("\"");
		foreach (var ch in value)
			builder.Append(ch == '\'' ? "'" : EscapeChar(ch));
		return builder.Append('"').ToString();
	}

	private static string RenderChar(char ch) => "'" + (ch == '\"' ? "\"" : EscapeChar(ch)) + "'";

	private static string EscapeChar(char ch) =>
		ch switch
		{
			'\'' => @"\'",
			'\"' => @"\""",
			'\\' => @"\\",
			'\a' => @"\a",
			'\b' => @"\b",
			'\f' => @"\f",
			'\n' => @"\n",
			'\r' => @"\r",
			'\t' => @"\t",
			'\v' => @"\v",
			_ => char.IsControl(ch) ? $"\\u{(int) ch:x4}" : ch.ToString(),
		};

	private static string RenderGenericParameters(Type[] genericParameters)
	{
		var stringBuilder = new StringBuilder();
		for (var index = 0; index < genericParameters.Length; index++)
		{
			var genericParameter = genericParameters[index];
			stringBuilder.Append((index == 0 ? "<" : "") +
				(genericParameter.GetTypeInfo().GenericParameterAttributes.HasFlag(GenericParameterAttributes.Covariant) ? "out " : "") +
				(genericParameter.GetTypeInfo().GenericParameterAttributes.HasFlag(GenericParameterAttributes.Contravariant) ? "in " : "") +
				genericParameter.Name +
				(index < genericParameters.Length - 1 ? ", " : "") +
				(index == genericParameters.Length - 1 ? ">" : ""));
		}
		return stringBuilder.ToString();
	}

	private static string RenderShortGenericParameters(Type[] genericParameters)
	{
		var stringBuilder = new StringBuilder();
		for (var index = 0; index < genericParameters.Length; index++)
		{
			var genericParameter = genericParameters[index];
			stringBuilder.Append((index == 0 ? "<" : "") +
				genericParameter.Name +
				(index < genericParameters.Length - 1 ? "," : "") +
				(index == genericParameters.Length - 1 ? ">" : ""));
		}
		return stringBuilder.ToString();
	}

	private static string RenderTypeName(TypeInfo typeInfo, ICollection<MemberInfo>? seeAlso = null, IReadOnlyList<Attribute>? attributes = null, byte[]? nullableContextFlags = null)
	{
		attributes ??= [];
		var tupleNames = GetTupleNames(attributes);
		var tupleNameIndex = 0;
		var nullableFlags = GetNullableFlags(attributes);
		if (nullableFlags.Length == 0)
			nullableFlags = nullableContextFlags ?? [];
		var nullableFlagIndex = 0;
		return RenderTypeName(typeInfo, seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex);
	}

	private static string RenderTypeName(TypeInfo typeInfo, ICollection<MemberInfo>? seeAlso, IReadOnlyList<string?> tupleNames, ref int tupleNameIndex, byte[] nullableFlags, ref int nullableFlagIndex)
	{
		if (typeInfo.IsByRef)
			return RenderTypeName(typeInfo.GetElementType()!.GetTypeInfo(), seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex);

		var nullableOfType = Nullable.GetUnderlyingType(typeInfo.AsType());
		if (nullableOfType is not null)
			return $"{RenderTypeName(nullableOfType.GetTypeInfo(), seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex)}?";

		var nullableSuffix = "";
		if (!typeInfo.IsValueType || typeInfo.IsGenericType)
		{
			if (nullableFlagIndex < nullableFlags.Length && nullableFlags[nullableFlagIndex] == 2)
				nullableSuffix = "?";
			if (nullableFlagIndex < nullableFlags.Length - 1)
				nullableFlagIndex++;
		}

		if (typeInfo.IsArray)
			return $"{RenderTypeName(typeInfo.GetElementType()!.GetTypeInfo(), seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex)}[]" + nullableSuffix;

		var builtIn = TryGetBuiltInTypeName(typeInfo.AsType());
		if (builtIn is not null)
			return builtIn + nullableSuffix;

		var renderedTupleTypes = RenderTupleTypes(typeInfo, seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex);
		if (renderedTupleTypes.Count > 1)
			return $"({string.Join(", ", renderedTupleTypes)})";

		seeAlso?.Add(typeInfo);

		return GetShortName(typeInfo) + RenderGenericArguments(typeInfo.GenericTypeArguments, seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex) + nullableSuffix;
	}

	private static List<string> RenderTupleTypes(TypeInfo typeInfo, ICollection<MemberInfo>? seeAlso, IReadOnlyList<string?> tupleNames, ref int tupleNameIndex, byte[] nullableFlags, ref int nullableFlagIndex)
	{
		var renderedTupleTypes = new List<string>();

		if (typeInfo.Namespace == "System" && typeInfo.Name.StartsWith("ValueTuple`", StringComparison.Ordinal))
		{
			var ourTupleNameIndex = tupleNameIndex;
			tupleNameIndex += CountTupleItems(typeInfo);

			var genericTypeArguments = typeInfo.GenericTypeArguments;
			while (true)
			{
				foreach (var genericTypeArgument in genericTypeArguments.Take(7))
				{
					var itemType = genericTypeArgument.GetTypeInfo();
					var renderedTupleType = RenderTypeName(itemType, seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex);
					var itemName = tupleNames.ElementAtOrDefault(ourTupleNameIndex++);
					if (itemName is not null)
						renderedTupleType += $" {itemName}";
					renderedTupleTypes.Add(renderedTupleType);
				}

				if (genericTypeArguments.Length < 8)
					break;

				genericTypeArguments = genericTypeArguments[7].GenericTypeArguments;
				tupleNameIndex++;
			}
		}

		return renderedTupleTypes;
	}

	private static int CountTupleItems(TypeInfo typeInfo) =>
		typeInfo.GenericTypeArguments.Length < 8 ? typeInfo.GenericTypeArguments.Length : 7 + CountTupleItems(typeInfo.GenericTypeArguments[7].GetTypeInfo());

	private static IReadOnlyList<string?> GetTupleNames(IEnumerable<Attribute> attributes) =>
		attributes.OfType<TupleElementNamesAttribute>().FirstOrDefault()?.TransformNames as IReadOnlyList<string?> ?? [];

	private static string RenderGenericArguments(Type[]? genericArguments, ICollection<MemberInfo>? seeAlso = null)
	{
		var tupleNameIndex = 0;
		var nullableFlagIndex = 0;
		return RenderGenericArguments(genericArguments, seeAlso, [], ref tupleNameIndex, [], ref nullableFlagIndex);
	}

	private static string RenderGenericArguments(Type[]? genericArguments, ICollection<MemberInfo>? seeAlso, IReadOnlyList<string?> tupleNames, ref int tupleNameIndex, byte[] nullableFlags, ref int nullableFlagIndex)
	{
		if (genericArguments is null)
			return "";

		var stringBuilder = new StringBuilder();
		for (var index = 0; index < genericArguments.Length; index++)
		{
			var genericArgument = genericArguments[index];
			stringBuilder.Append((index == 0 ? "<" : "") +
				RenderTypeName(genericArgument.GetTypeInfo(), seeAlso, tupleNames, ref tupleNameIndex, nullableFlags, ref nullableFlagIndex) +
				(index < genericArguments.Length - 1 ? ", " : "") +
				(index == genericArguments.Length - 1 ? ">" : ""));
		}
		return stringBuilder.ToString();
	}

	private static string? TryGetBuiltInTypeName(Type? type)
	{
		if (type == typeof(void))
			return "void";
		if (type == typeof(bool))
			return "bool";
		if (type == typeof(byte))
			return "byte";
		if (type == typeof(sbyte))
			return "sbyte";
		if (type == typeof(char))
			return "char";
		if (type == typeof(decimal))
			return "decimal";
		if (type == typeof(double))
			return "double";
		if (type == typeof(float))
			return "float";
		if (type == typeof(int))
			return "int";
		if (type == typeof(uint))
			return "uint";
		if (type == typeof(long))
			return "long";
		if (type == typeof(ulong))
			return "ulong";
		if (type == typeof(object))
			return "object";
		if (type == typeof(short))
			return "short";
		if (type == typeof(ushort))
			return "ushort";
		if (type == typeof(string))
			return "string";
		return null;
	}

	private static bool IsStatic(MemberInfo memberInfo)
	{
		if (memberInfo is TypeInfo typeInfo)
			return typeInfo is { IsClass: true, IsAbstract: true, IsSealed: true };

		if (memberInfo is EventInfo eventInfo)
			return eventInfo.AddMethod?.IsStatic is true;

		if (memberInfo is PropertyInfo propertyInfo)
			return (propertyInfo.GetMethod ?? propertyInfo.SetMethod)?.IsStatic ?? false;

		if (memberInfo is FieldInfo fieldInfo)
			return fieldInfo is { IsStatic: true, IsLiteral: false };

		if (memberInfo is MethodBase methodBase)
			return methodBase.IsStatic;

		return false;
	}

	private static bool IsAbstract(MemberInfo memberInfo)
	{
		if (memberInfo is TypeInfo { IsInterface: false } typeInfo)
			return typeInfo.IsAbstract;

		if (memberInfo.DeclaringType?.GetTypeInfo().IsInterface == true)
			return false;

		if (memberInfo is EventInfo eventInfo)
			return eventInfo.AddMethod is not null && IsAbstract(eventInfo.AddMethod);

		if (memberInfo is PropertyInfo propertyInfo)
		{
			return (propertyInfo.GetMethod is not null && IsAbstract(propertyInfo.GetMethod)) ||
				(propertyInfo.SetMethod is not null && IsAbstract(propertyInfo.SetMethod));
		}

		if (memberInfo is MethodBase methodBase)
			return methodBase.IsAbstract;

		return false;
	}

	private static bool IsVirtual(MemberInfo memberInfo)
	{
		if (memberInfo.DeclaringType?.GetTypeInfo().IsInterface == true)
			return false;

		if (memberInfo is EventInfo eventInfo)
			return eventInfo.AddMethod is not null && IsVirtual(eventInfo.AddMethod);

		if (memberInfo is PropertyInfo propertyInfo)
		{
			return (propertyInfo.GetMethod is not null && IsVirtual(propertyInfo.GetMethod)) ||
				(propertyInfo.SetMethod is not null && IsVirtual(propertyInfo.SetMethod));
		}

		if (memberInfo is MethodInfo methodInfo)
			return methodInfo is { IsVirtual: true, IsFinal: false } && methodInfo.GetRuntimeBaseDefinition()!.DeclaringType == methodInfo.DeclaringType;

		return false;
	}

	private static bool IsOverride(MemberInfo memberInfo)
	{
		if (memberInfo.DeclaringType?.GetTypeInfo().IsInterface == true)
			return false;

		if (memberInfo is EventInfo eventInfo)
			return eventInfo.AddMethod is not null && IsOverride(eventInfo.AddMethod);

		if (memberInfo is PropertyInfo propertyInfo)
		{
			return (propertyInfo.GetMethod is not null && IsOverride(propertyInfo.GetMethod)) ||
				(propertyInfo.SetMethod is not null && IsOverride(propertyInfo.SetMethod));
		}

		if (memberInfo is MethodInfo methodInfo)
			return methodInfo is { IsVirtual: true, IsFinal: false } && methodInfo.GetRuntimeBaseDefinition()!.DeclaringType != methodInfo.DeclaringType;

		return false;
	}

	private static bool IsConst(MemberInfo memberInfo) => (memberInfo as FieldInfo)?.IsLiteral ?? false;

	private static bool IsReadOnly(MemberInfo memberInfo) => (memberInfo as FieldInfo)?.IsInitOnly ?? false;

	private static bool IsFlagsEnum(MemberInfo memberInfo) =>
		memberInfo is TypeInfo { IsEnum: true } type && type.GetCustomAttributes<FlagsAttribute>().Any();

	private static bool IsRecord(Type type) => type.GetMethod("<Clone>$") is not null;

	private static bool IsBuiltInRecordMember(MemberInfo memberInfo)
	{
		if (memberInfo.DeclaringType is not { } declaringType || !IsRecord(declaringType))
			return false;

		return memberInfo switch
		{
			MethodInfo method => method.Name is "<Clone>$" or "Deconstruct" or "Equals" or "GetHashCode" or "op_Equality" or "op_Inequality" or "PrintMembers" or "ToString",
			PropertyInfo property => property.Name is "EqualityContract",
			ConstructorInfo constructor => !constructor.IsPublic && constructor.GetParameters().Select(x => x.ParameterType).SequenceEqual([declaringType]),
			_ => false,
		};
	}

	private static XmlDocVisibilityLevel GetVisibility(MemberInfo memberInfo) => GetVisibility(memberInfo, XmlDocVisibilityLevel.Protected);

	private static XmlDocVisibilityLevel GetVisibility(MemberInfo memberInfo, XmlDocVisibilityLevel protectedInternal)
	{
		if (memberInfo is TypeInfo typeInfo)
		{
			var visibility = GetTypeVisibility(typeInfo);
			return typeInfo.IsNested ? GetMostPrivate(visibility, GetTypeVisibility(typeInfo.DeclaringType!.GetTypeInfo(), protectedInternal)) : visibility;
		}

		if (memberInfo is EventInfo eventInfo)
			return GetMethodVisibility(eventInfo.AddMethod!, protectedInternal);

		if (memberInfo is PropertyInfo propertyInfo)
			return GetPropertyVisibility(propertyInfo, protectedInternal);

		if (memberInfo is FieldInfo fieldInfo)
			return GetFieldVisibility(fieldInfo, protectedInternal);

		if (memberInfo is MethodBase methodBase)
			return GetMethodVisibility(methodBase, protectedInternal);

		return XmlDocVisibilityLevel.Private;
	}

	private static XmlDocVisibilityLevel GetTypeVisibility(TypeInfo typeInfo, XmlDocVisibilityLevel protectedInternal = XmlDocVisibilityLevel.Protected)
	{
		if (typeInfo.IsPublic || typeInfo.IsNestedPublic)
			return XmlDocVisibilityLevel.Public;
		if (typeInfo.IsNestedFamORAssem)
			return protectedInternal;
		if (typeInfo.IsNestedFamily)
			return XmlDocVisibilityLevel.Protected;
		if (typeInfo.IsNestedAssembly || typeInfo.IsNestedFamANDAssem)
			return XmlDocVisibilityLevel.Internal;
		return XmlDocVisibilityLevel.Private;
	}

	private static XmlDocVisibilityLevel GetMethodVisibility(MethodBase methodBase, XmlDocVisibilityLevel protectedInternal = XmlDocVisibilityLevel.Protected)
	{
		if (methodBase.IsPublic)
			return XmlDocVisibilityLevel.Public;
		if (methodBase.IsFamilyOrAssembly)
			return protectedInternal;
		if (methodBase.IsFamily)
			return XmlDocVisibilityLevel.Protected;
		if (methodBase.IsAssembly || methodBase.IsFamilyAndAssembly)
			return XmlDocVisibilityLevel.Internal;
		return XmlDocVisibilityLevel.Private;
	}

	private static XmlDocVisibilityLevel GetPropertyVisibility(PropertyInfo propertyInfo, XmlDocVisibilityLevel protectedInternal = XmlDocVisibilityLevel.Protected)
	{
		var getMethod = propertyInfo.GetMethod;
		var setMethod = propertyInfo.SetMethod;
		if (getMethod is null && setMethod is null)
			throw new InvalidOperationException();

		if (getMethod is not null && setMethod is null)
			return GetMethodVisibility(getMethod);
		if (getMethod is null)
			return GetMethodVisibility(setMethod!);

		return GetMostPublic(
			GetMethodVisibility(getMethod, protectedInternal),
			GetMethodVisibility(setMethod!, protectedInternal));
	}

	private static XmlDocVisibilityLevel GetFieldVisibility(FieldInfo fieldInfo, XmlDocVisibilityLevel protectedInternal = XmlDocVisibilityLevel.Protected)
	{
		if (fieldInfo.IsPublic)
			return XmlDocVisibilityLevel.Public;
		if (fieldInfo.IsFamilyOrAssembly)
			return protectedInternal;
		if (fieldInfo.IsFamily)
			return XmlDocVisibilityLevel.Protected;
		if (fieldInfo.IsAssembly || fieldInfo.IsFamilyAndAssembly)
			return XmlDocVisibilityLevel.Internal;
		return XmlDocVisibilityLevel.Private;
	}

	private static string GetAccessModifier(MemberInfo memberInfo)
	{
		var visibility = GetVisibility(memberInfo, XmlDocVisibilityLevel.ProtectedInternal);
		return visibility switch
		{
			XmlDocVisibilityLevel.Public => "public",
			XmlDocVisibilityLevel.ProtectedInternal => "protected internal",
			XmlDocVisibilityLevel.Protected => "protected",
			XmlDocVisibilityLevel.Internal => "internal",
			XmlDocVisibilityLevel.Private => "private",
			_ => throw new InvalidOperationException(),
		};
	}

	private enum TypeKind
	{
		Unknown,
		Class,
		Interface,
		Struct,
		Enum,
		Delegate,
		Record,
	}

	private static TypeKind GetTypeKind(TypeInfo typeInfo)
	{
		if (typeof(Delegate).GetTypeInfo().IsAssignableFrom(typeInfo))
			return TypeKind.Delegate;
		if (IsRecord(typeInfo))
			return TypeKind.Record;
		if (typeInfo.IsClass)
			return TypeKind.Class;
		if (typeInfo.IsInterface)
			return TypeKind.Interface;
		if (typeInfo.IsEnum)
			return TypeKind.Enum;
		if (typeInfo.IsValueType)
			return TypeKind.Struct;
		return TypeKind.Unknown;
	}

	private enum MemberOrder
	{
		Constructor,
		LifetimeProperty,
		LifetimeField,
		LifetimeMethod,
		InstanceProperty,
		InstanceField,
		InstanceEvent,
		InstanceMethod,
		StaticProperty,
		StaticField,
		StaticEvent,
		StaticMethod,
		Operator,
		Type,
		Unknown,
	}

	private static MemberOrder GetMemberOrder(MemberInfo memberInfo) =>
		memberInfo switch
		{
			TypeInfo => MemberOrder.Type,
			ConstructorInfo => MemberOrder.Constructor,
			PropertyInfo propertyInfo => GetPropertyOrder(propertyInfo),
			EventInfo eventInfo => GetEventOrder(eventInfo),
			MethodInfo methodInfo => GetMethodOrder(methodInfo),
			FieldInfo fieldInfo => GetFieldOrder(fieldInfo),
			_ => MemberOrder.Unknown,
		};

	private static MemberOrder GetPropertyOrder(PropertyInfo propertyInfo)
	{
		var method = propertyInfo.GetMethod ?? propertyInfo.SetMethod!;
		if (!method.IsStatic)
			return MemberOrder.InstanceProperty;
		if (propertyInfo.PropertyType == propertyInfo.DeclaringType)
			return MemberOrder.LifetimeProperty;
		return MemberOrder.StaticProperty;
	}

	private static MemberOrder GetEventOrder(EventInfo eventInfo)
	{
		var method = eventInfo.AddMethod ?? eventInfo.RemoveMethod!;
		if (!method.IsStatic)
			return MemberOrder.InstanceEvent;
		return MemberOrder.StaticEvent;
	}

	private static MemberOrder GetMethodOrder(MethodInfo methodInfo)
	{
		if (methodInfo.Name.StartsWith("op_", StringComparison.Ordinal))
			return MemberOrder.Operator;
		if (!methodInfo.IsStatic)
			return MemberOrder.InstanceMethod;
		if (methodInfo.ReturnType == methodInfo.DeclaringType)
			return MemberOrder.LifetimeMethod;
		return MemberOrder.StaticMethod;
	}

	private static MemberOrder GetFieldOrder(FieldInfo fieldInfo)
	{
		if (!fieldInfo.IsStatic)
			return MemberOrder.InstanceField;
		if (fieldInfo.FieldType == fieldInfo.DeclaringType)
			return MemberOrder.LifetimeField;
		return MemberOrder.StaticField;
	}

	private static IEnumerable<T> OrderMembers<T>(IEnumerable<T> items, Func<T, MemberInfo> getMemberInfo) =>
		items.OrderBy(x => (int) GetMemberOrder(getMemberInfo(x)))
			.ThenBy(x => GetShortName(getMemberInfo(x)).ToString(), StringComparer.OrdinalIgnoreCase)
			.ThenBy(x => GetGenericArguments(getMemberInfo(x)).Length)
			.ThenBy(x => GetParameters(getMemberInfo(x)).Length)
			.ThenBy(x => GetParameterShortNames(getMemberInfo(x)), StringComparer.OrdinalIgnoreCase);

	private static MethodInfo? TryGetDelegateInvoke(MemberInfo memberInfo) =>
		memberInfo is TypeInfo typeInfo &&
		typeof(Delegate).GetTypeInfo().IsAssignableFrom(typeInfo) ? typeInfo.DeclaredMethods.FirstOrDefault(x => x.Name == "Invoke") : null;

	private static Type[] GetGenericArguments(MemberInfo memberInfo)
	{
		if (memberInfo is TypeInfo type)
			return type.GenericTypeParameters;

		return (memberInfo as MethodInfo)?.GetGenericArguments() ?? [];
	}

	private static ParameterInfo[] GetParameters(MemberInfo memberInfo)
	{
		if (TryGetDelegateInvoke(memberInfo) is { } delegateInvoke)
			return GetParameters(delegateInvoke);

		if (memberInfo is PropertyInfo propertyInfo)
			return propertyInfo.GetIndexParameters();

		return (memberInfo as MethodBase)?.GetParameters() ?? [];
	}

	private static string GetParameterShortNames(MemberInfo memberInfo) =>
		string.Join(", ", GetParameters(memberInfo).Select(x => RenderTypeName(x.ParameterType.GetTypeInfo())));

	private static bool IsLessDerived(TypeInfo a, TypeInfo b)
	{
		if (!a.IsAssignableFrom(b))
			return false;
		if (a.IsGenericType && b.IsGenericType && a.GetGenericTypeDefinition().GetTypeInfo() == b.GetGenericTypeDefinition().GetTypeInfo())
		{
			var parameters = a.GetGenericTypeDefinition().GetTypeInfo().GenericTypeParameters;
			for (var i = 0; i < parameters.Length; i++)
			{
				var paramAttributes = parameters[i].GetTypeInfo().GenericParameterAttributes;
				var aArgInfo = a.GenericTypeArguments[i].GetTypeInfo();
				var bArgInfo = b.GenericTypeArguments[i].GetTypeInfo();
				if (paramAttributes.HasFlag(GenericParameterAttributes.Contravariant) && !aArgInfo.IsAssignableFrom(bArgInfo))
					return false;
				if (paramAttributes.HasFlag(GenericParameterAttributes.Covariant) && aArgInfo.IsAssignableFrom(bArgInfo))
					return false;
			}
		}
		return true;
	}

	private static bool IsKeyword(string value) => s_keywords.Contains(value);

	private string ToMarkdown(XmlDocInline inline, MarkdownContext context)
	{
		var text = inline.Text ?? "";

		MemberInfo? seeMemberInfo = null;
		if (inline.SeeRef is not null)
			context.MembersByXmlDocName.TryGetValue(inline.SeeRef, out seeMemberInfo);

		if (text.Length == 0)
		{
			if (seeMemberInfo is not null)
				text = GetOperatorKeywordName(GetShortName(seeMemberInfo));
			else if (inline.SeeRef is not null)
				text = XmlDocUtility.GetShortNameForXmlDocRef(inline.SeeRef);
			else if (inline.LinkUrl is not null)
				text = inline.LinkUrl;
			else if (inline.LangWord is not null)
				text = SurroundCode(inline.LangWord);
		}

		if (text.Length != 0)
		{
			var isCode = inline.IsCode || seeMemberInfo is not null;
			if (isCode)
				text = SurroundCode(text);

			if (inline.IsParamRef || inline.IsTypeParamRef)
				text = $"*{text}*";

			text = WrapMarkdownRefLink(text, seeMemberInfo, context, isCode: inline.IsCode, linkUrl: inline.LinkUrl);
		}

		text = Regex.Replace(text, @"\s+", " ");

		return text;
	}

	private string WrapMarkdownRefLink(string text, MemberInfo? memberInfo, MarkdownContext context, bool isCode = false, string? linkUrl = null)
	{
		var extension = GetFileExtension();
		var xmlDocRef = memberInfo is null ? null : XmlDocUtility.GetXmlDocRef(memberInfo);
		var isLocal = xmlDocRef is not null && context.MembersByXmlDocName.ContainsKey(xmlDocRef);
		var externalDoc = isLocal || xmlDocRef is null ? null : FindExternalDocumentation(memberInfo);
		if (memberInfo is not null && xmlDocRef != XmlDocUtility.GetXmlDocRef(context.MemberInfo) && (isLocal || externalDoc is not null))
		{
			string path;

			var typeInfo = memberInfo as TypeInfo;
			if (context.MemberInfo is not null)
			{
				if (typeInfo is not null)
					path = $"{GetNamespaceUriName(typeInfo.Namespace)}/{GetSafeTypeUriName(typeInfo)}{extension}";
				else
					path = $"{GetNamespaceUriName(memberInfo.DeclaringType?.Namespace)}/{GetTypeUriName(memberInfo.DeclaringType!.GetTypeInfo())}/{GetMemberUriName(memberInfo)}{extension}";
			}
			else if (context.TypeInfo is not null)
			{
				if (typeInfo is not null)
					path = $"{GetNamespaceUriName(typeInfo.Namespace)}/{GetSafeTypeUriName(typeInfo)}{extension}";
				else
					path = $"{GetNamespaceUriName(memberInfo.DeclaringType?.Namespace)}/{GetTypeUriName(memberInfo.DeclaringType!.GetTypeInfo())}/{GetMemberUriName(memberInfo)}{extension}";
			}
			else
			{
				if (typeInfo is not null)
					path = $"{GetNamespaceUriName(typeInfo.Namespace)}/{GetSafeTypeUriName(typeInfo)}{extension}";
				else
					path = $"{GetNamespaceUriName(memberInfo.DeclaringType?.Namespace)}/{GetTypeUriName(memberInfo.DeclaringType!.GetTypeInfo())}/{GetMemberUriName(memberInfo)}{extension}";
			}

			if (!string.IsNullOrEmpty(context.PageLocation))
				path = MakeRelative(context.PageLocation, path);

			text = $"[{text}]({path})";
		}
		else if (linkUrl is not null)
		{
			text = $"[{text}]({linkUrl})";
		}

		return isCode ? text : EscapeHtml(text);
	}

	private string MakeRelative(string baseUri, string path)
	{
		var a = new Uri("file:///" + baseUri);
		var b = new Uri("file:///" + path);
		var rel = a.MakeRelativeUri(b);
		var result = rel.OriginalString;
		if (string.IsNullOrEmpty(result))
		{
			// then the file name is the link
			result = b.Segments.Last();
		}

		// generate explicit relative link, e.g. for GitLab wiki
		return result[0] == '.' ? result : $"./{result}";
	}

	private string? ToMarkdown(IEnumerable<XmlDocInline>? inlines, MarkdownContext context) =>
		inlines is null ? null : string.Concat(inlines.Select(x => ToMarkdown(x, context))).Trim();

	private IEnumerable<string> ToMarkdown(Collection<XmlDocBlock> blocks, MarkdownContext context)
	{
		for (var index = 0; index < blocks.Count; index++)
		{
			if (index != 0)
				yield return "";

			var block = blocks[index];

			if (block.ListKind is XmlDocListKind.Bullet or XmlDocListKind.Number)
			{
				var number = 0;
				while (true)
				{
					var prefix = new string(' ', block.ListDepth * 2) + (block.ListKind == XmlDocListKind.Number ? $"{++number}. " : "* ");
					var markdown = ToMarkdown(block.Inlines, context);

					if (block.IsListTerm)
					{
						markdown = $"**{markdown}**";

						var afterTermBlock = index + 1 < blocks.Count ? blocks[index + 1] : null;
						if (afterTermBlock is not null && afterTermBlock.ListKind == block.ListKind && afterTermBlock.ListDepth == block.ListDepth && !afterTermBlock.IsListTerm)
						{
							markdown += " – " + ToMarkdown(afterTermBlock.Inlines, context);
							index++;
						}
					}

					yield return prefix + markdown;

					var nextBlock = index + 1 < blocks.Count ? blocks[index + 1] : null;
					if (nextBlock is null || nextBlock.ListKind != block.ListKind)
						break;

					block = nextBlock;
					index++;
				}
			}
			else
			{
				if (block.IsCode)
				{
					yield return "```csharp";
					foreach (var inline in block.Inlines)
						yield return inline.Text!.Replace(Environment.NewLine, ActualNewLine, StringComparison.Ordinal);
					yield return "```";
				}
				else
				{
					var markdown = ToMarkdown(block.Inlines, context)!;
					if (block.IsListHeader || block.IsListTerm)
						markdown = $"**{markdown}**";
					yield return markdown;
				}
			}
		}
	}

	private sealed class MarkdownContext
	{
		public MarkdownContext(XmlDocFile xmlDocFile, IReadOnlyDictionary<string, MemberInfo> membersByXmlDocName, string assemblyFileName, string pageLocation)
		{
			XmlDocFile = xmlDocFile;
			MembersByXmlDocName = membersByXmlDocName;
			AssemblyFileName = assemblyFileName;
			PageLocation = pageLocation;
		}

		public MarkdownContext(MarkdownContext context, MemberInfo? memberInfo, string pageLocation)
		{
			XmlDocFile = context.XmlDocFile;
			MembersByXmlDocName = context.MembersByXmlDocName;
			AssemblyFileName = context.AssemblyFileName;
			PageLocation = pageLocation;

			if (memberInfo is TypeInfo typeInfo)
			{
				TypeInfo = typeInfo;
			}
			else if (memberInfo is not null)
			{
				TypeInfo = memberInfo.DeclaringType!.GetTypeInfo();
				MemberInfo = memberInfo;
			}
		}

		public TypeInfo? TypeInfo { get; }

		public MemberInfo? MemberInfo { get; }

		public XmlDocFile XmlDocFile { get; }

		public IReadOnlyDictionary<string, MemberInfo> MembersByXmlDocName { get; }

		public string AssemblyFileName { get; }

		public string PageLocation { get; }
	}

	private static readonly HashSet<string> s_keywords =
	[
		"abstract",
		"as",
		"base",
		"bool",
		"break",
		"byte",
		"case",
		"catch",
		"char",
		"checked",
		"class",
		"const",
		"continue",
		"decimal",
		"default",
		"delegate",
		"do",
		"double",
		"else",
		"enum",
		"event",
		"explicit",
		"extern",
		"false",
		"finally",
		"fixed",
		"float",
		"for",
		"foreach",
		"goto",
		"if",
		"implicit",
		"in",
		"int",
		"interface",
		"internal",
		"is",
		"lock",
		"long",
		"namespace",
		"new",
		"null",
		"object",
		"operator",
		"out",
		"override",
		"params",
		"private",
		"protected",
		"public",
		"readonly",
		"ref",
		"return",
		"sbyte",
		"sealed",
		"short",
		"sizeof",
		"stackalloc",
		"static",
		"string",
		"struct",
		"switch",
		"this",
		"throw",
		"true",
		"try",
		"typeof",
		"uint",
		"ulong",
		"unchecked",
		"unsafe",
		"ushort",
		"using",
		"virtual",
		"void",
		"volatile",
		"while",
	];
}
