#!/usr/bin/env pwsh
# DO NOT EDIT: generated by https://github.com/Faithlife/CodingGuidelines/tree/master/conventions/build-script
$ErrorActionPreference = 'Stop'
Push-Location $PSScriptRoot
try {
	dotnet publish ./tools/Build/Build.csproj --artifacts-path ./artifacts --nologo --verbosity quiet -tl:off
	if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
	dotnet ./artifacts/publish/Build/release/Build.dll $args
	if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}
finally {
	Pop-Location
}
