using NUnit.Framework;
using XmlDocGen.Core.Markdown;
using XmlDocGen.Core.Pages;
using XmlDocGen.Core.Sites;

namespace XmlDocGen.Tests.Markdown;

internal sealed class MarkdownLayerTests
{
	[Test]
	public void MarkdownRendersPropertyValuesAndOverviewTables()
	{
		var site = new MarkdownSiteBuilder(new XmlDocSiteBuilderSettings { PageMap = XmlDocPageMap.PerMember }).Build(TestSupport.CreateExampleTree());

		Assert.That(site.FindFile("ExampleAssembly/ExampleClass.md")?.Text, Does.Contain("## Public Members"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleClass.md")?.Text, Does.Contain("[Id { get; }](./ExampleClass/Id.md)"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleClass/Id.md")?.Text, Does.Contain("## Property Value"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleClass/Id.md")?.Text, Does.Contain("The ID."));
	}

	[Test]
	public void MarkdownRendersExternalLinksParamRefsAndSeeAlso()
	{
		var site = new MarkdownSiteBuilder(new XmlDocSiteBuilderSettings { PageMap = XmlDocPageMap.PerMember }).Build(TestSupport.CreateExampleTree());

		Assert.That(site.FindFile("ExampleAssembly/ExampleClass/HasHyperlinks.md")?.Text, Does.Contain("[more info](https://ejball.com/)"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleClass/ParameterReference.md")?.Text, Does.Contain("[`value`](#parameter-value)"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleDerivedClass/SeeAlso.md")?.Text, Does.Contain("## See Also"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleClass.md")?.Text, Does.Contain("[namespace ExampleAssembly](../ExampleAssembly.md#exampleassembly)"));
		Assert.That(site.FindFile("ExampleAssembly/ExampleClass.md")?.Text, Does.Contain("[interface IExampleContravariantInterface](./IExampleContravariantInterface-1.md)"));
	}

	[Test]
	public void MarkdownRendersGeneratedCommentsAndListTables()
	{
		var site = new MarkdownSiteBuilder(new XmlDocSiteBuilderSettings { PageMap = XmlDocPageMap.PerMember }).Build(TestSupport.CreateExampleTree());
		var longSummary = site.FindFile("ExampleAssembly/ExampleLongSummary.md")?.Text;

		Assert.That(site.FindFile("ExampleAssembly/ExampleClass.md")?.Text.ReplaceLineEndings("\n"), Does.EndWith("<!-- DO NOT EDIT: generated by XmlDocGen for ExampleAssembly -->\n"));
		Assert.That(longSummary, Does.Contain("| header 1 | header 2 | header 3 |"));
		Assert.That(longSummary, Does.Contain("| 1-1 | 1-2 | 1-3 |"));
	}

	[Test]
	public void PageRendererCanWriteFrontMatter()
	{
		var site = new MarkdownSiteBuilder(renderer: new FrontMatterRenderer()).Build(TestSupport.CreateExampleTree());

		Assert.That(site.FindFile("ExampleAssembly/ExampleClass.md")?.Text.ReplaceLineEndings("\n"), Does.StartWith("---\ntitle: ExampleClass\n---\n"));
	}

	private sealed class FrontMatterRenderer : MarkdownPageRenderer
	{
		protected override void WriteFrontMatter(MarkdownWriter writer, XmlDocPage page)
		{
			writer.WriteLine("---");
			writer.WriteLine("title: " + page.Nodes[0].Name);
			writer.WriteLine("---");
		}
	}
}
