using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1028", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1034", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1040", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1041", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1044", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1051", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1052", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1065", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1066", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1710", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1714", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1715", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1801", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA1805", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA2211", Justification = "for testing")]
[assembly: SuppressMessage("Design", "CA2225", Justification = "for testing")]
[assembly: SuppressMessage("Design", "SA1302", Justification = "for testing")]
[assembly: SuppressMessage("Design", "SA1314", Justification = "for testing")]
[assembly: SuppressMessage("Design", "SA1401", Justification = "for testing")]
