using XmlDocGen.Core.Nodes;
using XmlDocGen.Core.Pages;

namespace XmlDocGen.Core.Markdown;

/// <summary>A page renderer that emits Markdown.</summary>
public class MarkdownPageRenderer : XmlDocPageRenderer
{
	/// <summary>Initializes a new instance of the <see cref="MarkdownPageRenderer"/> class.</summary>
	public MarkdownPageRenderer(MarkdownRenderer? renderer = null)
	{
		Renderer = renderer ?? new MarkdownRenderer();
	}

	/// <summary>Gets the section renderer.</summary>
	protected MarkdownRenderer Renderer { get; }

	/// <inheritdoc />
	public override XmlDocRenderedFile RenderPage(XmlDocPage page, XmlDocPageContext context)
	{
		using var stringWriter = new StringWriter();
		var writer = new MarkdownWriter(stringWriter);
		WriteFrontMatter(writer, page);
		WriteHeader(writer, page, context);
		WriteBody(writer, page, context);
		WriteGeneratedComment(writer, page);
		return new XmlDocRenderedFile(page.Path + ".md", stringWriter.ToString());
	}

	/// <summary>Emits front matter for a page.</summary>
	protected virtual void WriteFrontMatter(MarkdownWriter writer, XmlDocPage page)
	{
	}

	/// <summary>Writes the page header.</summary>
	protected virtual void WriteHeader(MarkdownWriter writer, XmlDocPage page, XmlDocPageContext context)
	{
		writer.WriteHeading(1, GetTitle(page.Nodes[0]));
		writer.WriteLine();
	}

	/// <summary>Writes the page body.</summary>
	protected virtual void WriteBody(MarkdownWriter writer, XmlDocPage page, XmlDocPageContext context)
	{
		foreach (var (node, index) in page.Nodes.Select((node, index) => (node, index)))
		{
			if (index != 0)
			{
				writer.WriteLine();
				writer.WriteHeading(2, GetTitle(page, node));
			}

			writer.WriteLine();
			Renderer.WriteSummary(writer, node, context);
			if (node is XmlDocTypeNode or XmlDocMemberNode)
			{
				writer.WriteLine();
				Renderer.WriteSignature(writer, node, context);
			}
			Renderer.WriteChildren(writer, node, context);
			if (node is XmlDocMemberNode member)
			{
				Renderer.WriteParameters(writer, member, context);
				Renderer.WriteReturnValue(writer, member, context);
				Renderer.WritePropertyValue(writer, member, context);
				Renderer.WriteExceptions(writer, member, context);
			}
			Renderer.WriteRemarks(writer, node, context);
			Renderer.WriteExamples(writer, node, context);
			Renderer.WriteSeeAlso(writer, node, context);
		}
	}

	/// <summary>Writes the generated-file comment.</summary>
	protected virtual void WriteGeneratedComment(MarkdownWriter writer, XmlDocPage page)
	{
		writer.WriteLine();
		writer.WriteLine($"<!-- DO NOT EDIT: generated by XmlDocGen for {GetGeneratedAssemblyList(page)} -->");
	}

	private static string GetTitle(XmlDocNode node) => node.Name + " " + GetKindTitle(node);

	private static string GetTitle(XmlDocPage page, XmlDocNode node) => XmlDocPageHeadings.GetHeadingText(page, node) + " " + GetKindTitle(node);

	private static string GetKindTitle(XmlDocNode node)
	{
		return node switch
		{
			XmlDocAssemblyNode => "assembly",
			XmlDocNamespaceNode => "namespace",
			XmlDocTypeNode { Kind: XmlDocTypeKind.Struct } => "structure",
			XmlDocTypeNode type => type.Kind.ToString().ToLowerInvariant(),
			XmlDocMemberNode member => member.MemberKind.ToString().ToLowerInvariant(),
			_ => "node",
		};
	}

	private static string GetGeneratedAssemblyList(XmlDocPage page) => string.Join(", ", page.Nodes.Select(x => x.Assembly.ReflectionAssembly.GetName().Name).Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.OrdinalIgnoreCase));
}
